image: mischief/docker-golang
env:
  - GOPATH=/var/cache/drone
script:
  - go build
  - go test -v
publish:
  docker:
  	docker_host: tcp://10.3.1.12:2375
  	image_name: 10.3.1.2:5000/drone-test
  	keep_build: true