image: daocloud/docker
env:
  - GOPATH=/var/cache/drone
script:
#  - go build
#  - go test -v
publish:
  docker:
    docker_host: unix:///var/run/docker.sock
    image_name: 192.168.1.36:5000/drone-test
    keep_build: true
    tag: v1.0
